# All logic to embbeding movie

#### Variables a conciderar
- adult (2)
- original_lenguaje (4)
- title (3)
- keywords (5)
- popularity (3)
- date (year) (3)
- director (5)
- actors (5)
- vote_average (3)
- vote_count (3)
- Genre (7)
-------------------------
43

## Connect to DB

In [1]:
import mysql.connector
import pandas as pd
#-----------------------------
import random
import mmh3
import numpy as np
#-----------------------------
import gensim.downloader as api
import ast
#-----------------------------
from annoy import AnnoyIndex
import faiss

In [2]:
config = {
    'host': '127.0.0.1',
    'port':'3307',
    'user': 'REG',
    'password': 'Aa123456',
    'database': 'TV_MOVIES_DB'
}

In [9]:
# conexion = mysql.connector.connect(**config)
# cursor = conexion.cursor()
# consulta = "SELECT * FROM Movies WHERE YEAR(release_date) = 2021;"
# cursor.execute(consulta)

# results = cursor.fetchall()
# column_names = [desc[0] for desc in cursor.description]

# movie_df = pd.DataFrame(results, columns=column_names)

In [11]:
conexion = mysql.connector.connect(**config)
cursor = conexion.cursor()
consulta = "SELECT * FROM Movies"
cursor.execute(consulta)

results = cursor.fetchall()
column_names = [desc[0] for desc in cursor.description]

movie_df = pd.DataFrame(results, columns=column_names)

In [12]:
movie_df.head(2)

,id,id_tmdb,adult,backdrop_path,original_lenguaje,overview,keywords,popularity,poster_path,release_date,title,director,actors,vote_average,vote_count,image_path,created_at
0,1,565426,0,/txaC2mhUhW0H0r31N6KzRTaz1rL.jpg,en,Lara Jean and Peter have just taken their roma...,"['lara jean', 'romance pretend', 'real recipie...",3.951,/maib5VlmEqp5xlN8lptnBSftp2o.jpg,2020-02-03,To All the Boys: P.S. I Still Love You,Michael Fimognari,"['Lana Condor', 'Noah Centineo', 'Jordan Fishe...",6.822,2669,Data/img_recommendMe/565426_to_all_the_boys_ps...,2026-02-10 17:02:24

In [13]:
batman_movie = movie_df.iloc[110]
batman_movie

IndexError: single positional indexer is out-of-bounds

## Get all vectors individualy

### Get adult vector

In [14]:
def multiply_num_vector(num, dimensions=2):
    vector = []

    for i in range(dimensions):
        vector.append(float(num))

    return vector

In [10]:
multiply_num_vector(batman_movie['adult'],2)

[0.0, 0.0]

### Get original lenguaje vector

In [15]:
def hashing_trick(text, dimensions=64, seed_offset=0):

    if text == "" or text == None or text == []:
        return np.zeros(dimensions, dtype=np.float32)

    if not text or not isinstance(text, str):
        text = str(text)
    
    hash_num = mmh3.hash(text, seed=42)
    
    vector = np.zeros(dimensions, dtype=np.float32)
    
    prime1 = 2654435761  
    prime2 = 5915587277
    
    for i in range(dimensions):

        seed = (hash_num ^ (i * prime1) ^ (seed_offset * prime2)) & 0xFFFFFFFF
        
        rng = np.random.RandomState(seed)

        value = rng.uniform(low=-10.0, high=10.0)
        vector[i] = value
    
    return vector

In [12]:
hashing_trick(batman_movie['original_lenguaje'],4)

array([ 3.4582613, -8.665419 , -4.83918  ,  9.013555 ], dtype=float32)

### Get title vector

In [16]:
def hashing_trick_list(list_text, dimensions=64, seed_offset=0):

    if list_text == "" or list_text == None or list_text == []:
        return np.zeros(dimensions, dtype=np.float32)

    text_vectors = []
    for text in list_text:
        if not text or not isinstance(text, str):
            text = str(text)
        
        hash_num = mmh3.hash(text, seed=42)
        
        vector = np.zeros(dimensions, dtype=np.float32)
        
        prime1 = 2654435761  
        prime2 = 5915587277
        
        for i in range(dimensions):
    
            seed = (hash_num ^ (i * prime1) ^ (seed_offset * prime2)) & 0xFFFFFFFF
            
            rng = np.random.RandomState(seed)
    
            value = rng.uniform(low=-10.0, high=10.0)
            vector[i] = value
            text_vectors.append(vector)
    
    return np.mean(text_vectors, axis=0)

In [14]:
list_title = list(batman_movie['title'])
hashing_trick_list(list_title,3)

array([-0.09674486,  0.4463041 , -3.394736  ], dtype=float32)

### Get keywords vector

In [22]:
model = api.load("glove-wiki-gigaword-50")

In [17]:
def top_words_5_vector(list_text, reducir_a_5D=True):

    if list_text == "" or list_text == None or list_text == []:
        return np.zeros(5, dtype=np.float32)

    top_5_vectors = []
    for text in list_text:
    
        words = text.lower().split()
        words_vectors = []
    
        for word in words:
            try:
                vector_50d = model[word]
            except KeyError:
                vector_50d = np.zeros(50)
            
            if not reducir_a_5D:
                return vector_50d
            
            vector_5d = np.zeros(5)
            bloque = 50 // 5 
    
            for i in range(5):
                inicio = i * bloque
                fin = inicio + bloque
                vector_5d[i] = np.mean(vector_50d[inicio:fin])
                
            words_vectors.append(vector_5d)
        top_5_vectors.append(np.mean(words_vectors, axis=0))
        
    return np.round(np.mean(top_5_vectors, axis=0), 7)

In [17]:
keywords_list = ast.literal_eval(batman_movie['keywords'])
top_words_5_vector(keywords_list)

array([ 0.0737301,  0.0821995, -0.0836377,  0.0037927, -0.0998564])

### Get popularity vector

In [18]:
print(multiply_num_vector(batman_movie['popularity'], 3))

[1.482, 1.482, 1.482]

### Get date vector

In [18]:
def date_vector(release_date, num=3):
    year = str(release_date).split('-')[0]
    year = int(year) - 2000
    return multiply_num_vector(year, num)

In [20]:
date_vector(batman_movie['release_date'])

[20.0, 20.0, 20.0]

### Get director vector

In [21]:
hashing_trick(batman_movie['director'] ,5)

array([7.68838  , 2.8533568, 5.6163015, 4.477386 , 1.2732053],
      dtype=float32)

### Get actors vector

In [22]:
actors_list = ast.literal_eval(batman_movie['actors'])
hashing_trick_list(actors_list,5)

array([-0.95966446,  2.394908  , -0.9665145 , -2.945136  , -1.0375808 ],
      dtype=float32)

### Get vote_average vector

In [23]:
multiply_num_vector(batman_movie['vote_average'], 3)

[6.6, 6.6, 6.6]

### Get vote_count

In [24]:
vote_count = float(batman_movie['vote_count']) / 1000
multiply_num_vector(vote_count, 3)

[0.064, 0.064, 0.064]

### Get gender vector

In [19]:
def get_gender_movie(movie_id, dimension=7):

    conexion = mysql.connector.connect(**config)
    cursor = conexion.cursor()
    consulta = "SELECT genre_id FROM Movie_Genres Where movie_id = " + str(movie_id)
    cursor.execute(consulta)
    
    results = cursor.fetchall()
    gender = [x[0] for x in results]
    if gender == "" or gender == None:
        return np.zeros(dimension, dtype=np.float32)
    return hashing_trick_list(gender,dimension)

In [26]:
get_gender_movie(batman_movie["id"])

array([ 2.449926  ,  3.220671  , -6.8632817 ,  4.2147765 ,  1.019425  ,
       -0.12754276,  2.0236647 ], dtype=float32)

### Generate new Dataframe Vectorized

In [20]:
def safe_literal_eval(x):
    if pd.isna(x):
        return []
    
    if isinstance(x, list):
        return x  # Ya es lista
    
    if isinstance(x, str):
        x = x.strip()
        if x and x.startswith('[') and x.endswith(']'):
            try:
                return ast.literal_eval(x)
            except:
                pass
        return [x] if x else []
    
    return []

In [23]:
df_vectorized = pd.DataFrame({
    "id": movie_df['id'],
    'adult': movie_df['adult'].apply(lambda x: multiply_num_vector(x, 2)),
    'original_lenguaje': movie_df['original_lenguaje'].apply(lambda x: hashing_trick(x, 4)),
    'title': movie_df['title'].apply(lambda x: hashing_trick_list(x, 3)),
    'keywords': movie_df['keywords'].apply(lambda x: top_words_5_vector(ast.literal_eval(x))),
    'popularity': movie_df['popularity'].apply(lambda x: multiply_num_vector(x, 3)),
    'release_date': movie_df['release_date'].apply(lambda x: date_vector(x, 3)),
    'director': movie_df['director'].apply(lambda x: hashing_trick(x, 5)),
    'actors': movie_df['actors'].apply(lambda x: hashing_trick_list(safe_literal_eval(x), 5)),
    'vote_average': movie_df['vote_average'].apply(lambda x: multiply_num_vector(x, 3)),
    'vote_count': movie_df['vote_count'].apply(lambda x: multiply_num_vector(float(x) / 1000, 3)),
    'gender': movie_df['id'].apply(lambda x: get_gender_movie(x,7))
})

vector_columns = ['adult','original_lenguaje','title','keywords','popularity',
                 'release_date', 'director', 'actors', 'vote_average',
                 'vote_count', 'gender']
df_vectorized['movie_vector'] = df_vectorized[vector_columns].apply(
    lambda row: np.concatenate([row[col] for col in vector_columns]),
    axis=1
)

In [24]:
df_vectorized.head()

,id,adult,original_lenguaje,title,keywords,popularity,release_date,director,actors,vote_average,vote_count,gender,movie_vector
0,1,"[0.0, 0.0]","[3.4582613, -8.665419, -4.83918, 9.013555]","[-2.15566, -2.3455803, 1.3848987]","[0.0624972, 0.0605411, -0.0829374, 0.1231957, ...","[3.951, 3.951, 3.951]","[20.0, 20.0, 20.0]","[-0.5351226, -7.3357987, 8.158843, -9.692719, ...","[-3.5462797, 3.3527627, -0.89187896, 1.8922313...","[6.822, 6.822, 6.822]","[2.669, 2.669, 2.669]","[4.295691, -3.1224782, -0.46065953, -0.0377524...","[0.0, 0.0, 3.458261251449585, -8.6654186248779..."

In [25]:
len(df_vectorized['movie_vector'].iloc[0])

43

In [26]:
df_vectorized['movie_vector'].iloc[0]

array([ 0.        ,  0.        ,  3.45826125, -8.66541862, -4.83917999,
        9.01355457, -2.15565991, -2.34558034,  1.38489866,  0.0624972 ,
        0.0605411 , -0.0829374 ,  0.1231957 ,  0.0514495 ,  3.951     ,
        3.951     ,  3.951     , 20.        , 20.        , 20.        ,
       -0.53512257, -7.33579874,  8.15884304, -9.69271946, -9.40436363,
       -3.54627967,  3.3527627 , -0.89187896,  1.89223135,  0.9273572 ,
        6.822     ,  6.822     ,  6.822     ,  2.669     ,  2.669     ,
        2.669     ,  4.29569101, -3.12247825, -0.46065953, -0.03775242,
       -4.18693304, -8.21774006, -3.72150183])

In [27]:
df_vectorized.shape

(1, 13)

## Test CSV

In [30]:
movie_df = pd.read_csv('../movies_db.csv')

In [32]:
movie_df.head(2)

,id,id_tmdb,adult,backdrop_path,original_lenguaje,overview,keywords,popularity,poster_path,release_date,title,director,actors,vote_average,vote_count,image_path,created_at
0,1,522627,0,/tintsaQ0WLzZsTMkTiqtMB3rfc8.jpg,en,American expat Mickey Pearson has built a high...,"['profitable marijuana', 'expat mickey', 'lond...",8.102,/jtrhTYB7xSrJxR1vusu99nvnZ1g.jpg,2020-01-01,The Gentlemen,Guy Ritchie,"['Matthew McConaughey', 'Charlie Hunnam', 'Mic...",7.670,6379,Data/img_recommendMe/522627_the_gentlemen.jpg,2026-01-29 15:07:32
1,2,593402,0,/8TiYxxck4kfKwXAAdi6aZLeQd5L.jpg,it,Checco is a young Apulian entrepreneur dreamer...,"['checco', 'apulian entrepreneur', 'sushi rest...",7.025,/CqUxog8F6aaK97RYh8YXhv3NDL.jpg,2020-01-01,Tolo Tolo,Checco Zalone,"['Checco Zalone', 'Manda Touré', 'Nassor Said ...",6.111,1296,Data/img_recommendMe/593402_tolo_tolo.jpg,2026-01-29 15:07:35

In [34]:
for index, row in movie_df.iterrows():
    print(row['id'], row['id_tmdb'], row['original_lenguaje'])

1 522627 en
2 593402 it
3 430155 ru
4 448119 en
5 630220 it
6 609031 uk
7 666180 en
8 646453 en
9 656844 en
10 639289 en
11 443791 en
12 575426 it
13 592834 en
14 590869 it
15 632309 en
16 526019 en
17 584850 hi
18 607313 te
19 527534 en
20 631430 en
21 550738 fr
22 628241 te
23 662844 en
24 38700 en
25 586461 en
26 575718 ko
27 613345 fr
28 613319 fr
29 474764 en
30 633172 de
31 609242 es
32 620924 en
33 639798 es
34 573730 ja
35 665090 tr
36 651070 en
37 642700 pl
38 566397 ko
39 604822 zh
40 487631 fr
41 604362 ko
42 653574 en
43 596247 es
44 652483 pt
45 503917 cn
46 492611 en
47 442065 en
48 603770 zh
49 653643 en
50 522241 en
51 619918 no
52 548473 en
53 653723 en
54 666959 sv
55 656690 en
56 653601 en
57 552532 en
58 575774 en
59 532870 en
60 653744 en
61 567970 en
62 589970 fr
63 582922 fr
64 451184 en
65 621749 en
66 606954 it
67 648990 es
68 542224 en
69 664593 tr
70 627463 en
71 466622 en
72 528761 en
73 653567 en
74 631132 ja
75 565426 en
76 495764 en
77 571625 ko
78 649755 de
79 586742 da
80 560391 en
81 635199 ja
82 664413 pl
83 670466 en
84 525428 en
85 552687 ja
86 454626 en
87 539537 en
88 736509 en
89 584355 fr
90 653910 de
91 556678 en
92 622469 fr
93 623926 es
94 610461 es
95 505225 en
96 658760 de
97 616803 sv
98 38258 en
99 526007 en
100 571648 ko
101 481848 en
102 613614 it
103 592279 ru
104 619594 en
105 657811 de
106 555974 en
107 571265 ja
108 705862 ja
109 566927 en
110 677640 ro
111 576560 en
112 571785 ko
113 618355 en
114 570670 en
115 658156 fr
116 582911 fr
117 613362 fr
118 514207 ru
119 575088 ru
120 608317 it
121 671812 it
122 457335 en
123 678489 zh
124 617499 uk
125 476389 en
126 518978 en
127 667018 es
128 399363 en
129 342470 en
130 489326 en
131 508439 en
132 661227 en
133 661804 fr
134 613367 fr
135 338762 en
136 529485 en
137 594669 hi
138 566872 en
139 627725 en
140 680734 en
141 590854 pl
142 590575 en
143 581600 en
144 502425 en
145 507441 en
146 597233 en
147 558582 en
148 668195 it
149 382748 en
150 514847 en
151 446893 en
152 480857 en
153 600479 fr
154 567965 en
155 585244 en
156 637860 es
157 653575 en
158 574396 en
159 675253 en
160 618228 af
161 449756 en
162 539617 en
163 606717 hi
164 560008 en
165 605802 en
166 595671 en
167 648371 en
168 665135 en
169 711705 en
170 670426 en
171 526120 nl
172 665251 ja
173 682589 en
174 686002 en
175 681019 pl
176 674944 es
177 614971 it
178 655431 ja
179 491926 en
180 660609 en
181 340102 en
182 555457 en
183 617786 en
184 689249 es
185 734353 en
186 470610 en
187 686142 en
188 624808 en
189 664767 en
190 526052 en
191 550231 en
192 680593 en
193 522655 en
194 598215 en
195 581577 de
196 658751 de
197 560044 en
198 545609 en
199 627661 en
200 656563 pt
201 602147 en
202 689723 en
203 597219 en
204 530956 en
205 618344 en
206 560204 en
207 482273 en
208 545237 en
209 582596 en
210 693158 en
211 691812 en
212 661845 en
213 567608 en
214 513268 en
215 660330 fr
216 576156 en
217 638706 en
218 415311 en
219 713474 en
220 653664 en
221 623666 es
222 635237 en
223 620883 es
224 647785 en
225 696374 en
226 475430 en
227 602291 ko
228 805627 ja
229 339095 en
230 602296 ko
231 606679 en
232 710717 en
233 703134 en
234 581859 en
235 714842 en
236 599521 en
237 522098 en
238 614292 it
239 702936 en
240 762632 en
241 698783 en
242 667520 ja
243 514593 en
244 586351 es
245 707886 en
246 521531 en
247 682426 tr
248 706503 fr
249 653610 en
250 714351 en
251 484297 en
252 614696 ko
253 639247 en
254 531876 en
255 716145 en
256 554908 en
257 714338 hi
258 575659 de
259 429422 en
260 696826 it
261 663459 en
262 520946 en
263 531454 en
264 677638 en
265 615761 de
266 658905 fr
267 694234 it
268 595148 en
269 598133 en
270 621707 en
271 539885 en
272 614427 it
273 446574 en
274 619592 en
275 716706 en
276 686245 en
277 539181 en
278 606625 en
279 635918 en
280 698860 ja
281 608195 en
282 583984 en
283 385103 en
284 679989 fr
285 521034 en
286 522444 en
287 547016 en
288 516486 en
289 659991 en
290 587792 en
291 709717 th
292 638045 en
293 665488 fr
294 659959 fr
295 581392 ko
296 608649 it
297 667071 fr
298 582218 en
299 625568 en
300 714375 en
301 724106 ko
302 718840 en
303 603119 en
304 611395 zh
305 579583 en
306 702525 en
307 718867 en
308 587496 en
309 645489 hi
310 601844 en
311 594718 ru
312 527660 en
313 726208 es
314 583083 en
315 653615 en
316 714521 en
317 614626 en
318 523977 en
319 645484 hi
320 601165 en
321 524047 en
322 711321 fr
323 606906 ko
324 703155 es
325 635503 hi
326 493065 en
327 671583 en
328 589615 hi
329 724089 en
330 661747 en
331 664297 en
332 761772 de
333 703771 en
334 581526 ko
335 628917 en
336 513584 en
337 696002 en
338 531499 en
339 682153 ja
340 612706 en
341 667154 en
342 599335 ko
343 520318 en
344 606234 en
345 637969 en
346 400160 en
347 508935 zh
348 653598 en
349 517412 en
350 454433 en
351 605116 en
352 726664 en
353 390635 ja
354 666219 en
355 722926 en
356 582885 fr
357 718444 en
358 501738 cs
359 649392 en
360 651135 it
361 623958 en
362 675490 en
363 610201 en
364 523781 en
365 675476 ja
366 679888 es
367 508570 en
368 718400 en
369 621013 en
370 626393 en
371 577922 en
372 632632 ja
373 634233 en
374 618354 en
375 736485 en
376 721452 en
377 703745 en
378 736759 en
379 611808 fr
380 726887 en
381 659986 en
382 501979 en
383 517096 ru
384 425001 en
385 594328 en
386 546724 en
387 500840 en
388 715239 en
389 734309 en
390 733006 en
391 728796 en
392 731738 en
393 660004 fr
394 725273 en
395 712150 fr
396 644090 en
397 613504 en
398 627290 en
399 658777 de
400 739291 es
401 553604 en
402 606523 ko
403 671577 en
404 594084 en
405 337401 en
406 724989 en
407 682110 en
408 619443 es
409 653578 en
410 592656 en
411 539529 ar
412 616331 fr
413 509635 en
414 697064 en
415 623491 en
416 665139 it
417 730585 en
418 730647 ko
419 728142 en
420 632666 en
421 642121 ja
422 605133 en
423 547017 en
424 499932 en
425 737802 es
426 616251 en
427 346687 en
428 587609 ru
429 586032 en
430 552269 en
431 726739 en
432 701175 es
433 615115 en
434 664301 en
435 662401 ko
436 618245 uk
437 714099 it
438 533514 ja
439 479259 en
440 613370 fr
441 467342 en
442 715658 en
443 737157 en
444 497582 en
445 344031 en
446 599377 fr
447 492008 ko
448 734438 fr
449 741592 en
450 580175 da
451 669665 it
452 572299 en
453 684684 en
454 524216 en
455 755812 fr
456 556984 en
457 541305 en
458 739010 en
459 621870 en
460 656274 fr
461 653606 en
462 741612 en
463 728116 mr
464 664280 en
465 589174 ko
466 733156 en
467 694919 en
468 601297 fr
469 719410 zh
470 659290 it
471 655080 en
472 705715 it
473 635389 zh
474 528085 en
475 737568 en
476 606876 en
477 554761 en
478 544075 en
479 667141 en
480 435615 en
481 586393 ja
482 575417 en
483 724475 en
484 604578 en
485 567971 en
486 589612 en
487 660982 en
488 716258 en
489 721656 en
490 715123 en
491 617505 en
492 320846 de
493 749395 en
494 540414 en
495 711017 da
496 654902 it
497 522406 en
498 613093 es
499 740903 en
500 630566 en
501 720395 en
502 548755 en
503 725649 es
504 610359 en
505 728773 en
506 575776 en
507 732713 en
508 523366 en
509 572751 en
510 618353 en
511 643550 en
512 613377 fr
513 624963 en
514 505746 no
515 740996 ko
516 787009 en
517 743888 it
518 659994 en
519 670439 en
520 643612 en
521 720026 en
522 635302 ja
523 710356 en
524 590223 en
525 505379 en
526 728123 sv
527 560050 en
528 651610 en
529 637053 en
530 688301 ja
531 585744 fr
532 770156 en
533 602211 en
534 670266 en
535 651881 fr
536 744750 en
537 611751 fr
538 632304 en
539 726239 en
540 516632 en
541 624484 it
542 575446 es
543 524840 en
544 661950 en
545 660713 ja
546 748685 zh
547 549294 en
548 752721 sv
549 740985 en
550 741074 en
551 632322 en
552 652004 en
553 746817 en
554 756499 en
555 744738 en
556 741011 en
557 560144 en
558 554585 es
559 441130 en
560 531219 en
561 615665 en
562 590995 en
563 661229 fr
564 571384 en
565 602654 en
566 654894 it
567 758510 pt
568 670428 en
569 770922 en
570 688258 en
571 717675 es
572 767585 zh
573 671039 fr
574 735595 de
575 621151 en
576 729648 en
577 579828 ru
578 579831 ru
579 596161 en
580 728552 ru
581 734280 en
582 755340 wo
583 738646 en
584 556501 en
585 622855 en
586 759024 it
587 761563 en
588 592984 en
589 603673 hi
590 644831 en
591 653734 en
592 754800 de
593 712178 fr
594 753756 fr
595 551804 en
596 650783 en
597 527400 en
598 749618 es
599 658412 hi
600 595228 ta
601 723343 ja
602 614560 en
603 758935 en
604 558574 en
605 568467 en
606 732670 en
607 654028 en
608 733317 en
609 761053 en
610 663870 da
611 643882 en
612 641501 fr
613 642208 en
614 546121 en
615 728754 ja
616 502033 en
617 656561 en
618 787428 en
619 590706 en
620 592643 en
621 575604 ko
622 529203 en
623 733740 sr
624 615667 en
625 768141 en
626 634544 en
627 611114 en
628 520172 en
629 653708 en
630 779019 ja
631 680041 ja
632 353047 en
633 526702 en
634 746045 en
635 575089 zh
636 764079 en
637 653658 es
638 447362 en
639 654905 it
640 717021 en
641 733032 en
642 757388 en
643 727097 en
644 752455 en
645 771185 en
646 458576 en
647 633908 en
648 646593 en
649 649918 es
650 627103 en
651 593655 en
652 723072 en
653 662546 en
654 652962 en
655 637202 ja
656 636565 it
657 721625 en
658 664177 fr
659 614911 en
660 602301 ko
661 576920 ru
662 623856 en
663 521007 en
664 717634 en
665 628333 en
666 540023 en
667 676839 es
668 582014 en
669 724717 en
670 768939 en
671 464052 en
672 568994 en
673 651571 en
674 549514 en
675 647781 en
676 759902 en
677 854765 en
678 751496 es
679 651589 es
680 634521 ja
681 519056 en
682 774372 en
683 600354 en
684 757860 zh
685 589754 ru
686 585257 ru
687 559974 cn
688 508442 en
689 615677 en
690 776670 eu
691 661914 en
692 652837 ja
693 581032 en
694 662708 ja
695 655437 ja
696 641662 en
697 567797 en
698 675327 en
699 761830 it
700 681260 en
701 767304 en
702 773569 zh
703 618851 ja
704 732203 ja
705 732450 en
706 628534 en
707 626392 ta
708 788672 en
709 526811 fr
710 586101 en
711 532865 en
712 681435 te
713 634528 en
714 550205 en
715 775996 en
716 783753 ko
717 766208 en
718 618416 en
719 776797 zh
720 644083 en
721 706972 en
722 766931 en
723 630586 en
724 777620 en
725 602269 en
726 522466 en
727 458220 en
728 556867 en
729 793896 en
730 695932 ja
731 587996 es
732 581734 en
733 698320 en
734 644092 en
735 722913 en
736 500458 pt
737 736146 ja
738 660335 en
739 683127 ja
740 679548 en
741 682377 en
742 778814 en
743 801528 en
744 581389 ko
745 670129 en
746 613911 en
747 734519 ja
748 586791 en
749 686548 en
750 791570 ja
751 587130 en
752 663558 zh
753 682587 en
754 631583 en
755 588921 en
756 587807 en
757 633802 ru
758 784500 ja
759 649087 sv
760 664236 en
761 643586 en
762 611698 zh
763 758891 zh
764 598331 en
765 786300 en
766 614409 en
767 615643 en
768 583406 en
769 644583 en
770 672647 en
771 598896 en
772 602666 zh
773 665888 en
774 506281 en
775 758902 zh
776 599960 en
777 599281 en
778 752803 zh
779 667276 es
780 629028 ko
781 576784 ru
782 656940 en
783 513310 en
784 601666 en
785 579051 en
786 706872 ml
787 779280 ru
788 785976 pt
789 412656 en
790 771502 it
791 682254 en
792 676845 es
793 741228 en
794 728118 sr
795 800728 en
796 544401 en
797 580532 en
798 654754 en
799 801335 en
800 793967 en
801 666750 en
802 527774 en
803 779047 en
804 583689 en
805 797861 en
806 630004 en
807 484718 en
808 793002 en
809 760875 en
810 793723 fr
811 631058 en
812 283566 ja
813 676150 es
814 599025 ru
815 638597 en
816 630520 es
817 681887 en
818 635012 en
819 795859 en
820 795230 en
821 712121 pl
822 709629 es
823 675575 en
824 785534 tr
825 791469 en
826 669363 ar
827 795514 en
828 791373 en
829 615457 en
830 797394 ru
831 717694 sk
832 583833 ru
833 792001 es
834 802443 en
835 673319 en
836 798141 en
837 399566 en
838 801058 en
839 522478 en
840 578908 en
841 664300 en
842 699102 en
843 789413 en
844 595813 en
845 860623 en
846 632357 en
847 566076 en
848 797787 zh
849 529106 ru
850 811634 zh
851 802504 nl
852 805195 en
853 813258 en
854 741434 ja
855 660006 fr
856 803923 en
857 773147 it
858 786584 en
859 460465 en
860 676842 es
861 597890 en
862 603768 zh
863 615678 en
864 661930 fr
865 795811 ja
866 586047 ko
867 774454 en
868 589761 ru
869 796849 ja
870 664601 en
871 550524 en
872 662638 ja
873 786110 en
874 763568 en
875 808228 en
876 804435 en
877 602302 ko
878 637649 en
879 501929 en
880 806643 en
881 797294 en
882 741636 en
883 602063 ja
884 809314 en
885 776515 en
886 525660 cn
887 736069 en
888 812592 pt
889 823087 en
890 746781 fa
891 567189 en
892 631060 en
893 820492 en
894 573680 en
895 809910 en
896 808023 en
897 639557 zh
898 811367 en
899 810271 en
900 641960 en
901 760195 en
902 578701 en
903 675024 es
904 859041 zh
905 805051 en
906 534072 en
907 810223 en
908 557950 en
909 611489 en
910 602734 en
911 679844 hi
912 471498 fr
913 822010 en
914 520663 en
915 769749 en
916 717192 nl
917 767452 it
918 503736 en
919 670343 fa
920 797946 en
921 823855 en
922 726684 fr
923 740658 zh
924 385128 en
925 638965 fr
926 754765 fr
927 805058 ko
928 637693 en
929 821390 en
930 520763 en
931 641668 en
932 807597 en
933 603206 en
934 423108 en
935 337404 en
936 659940 da
937 817451 en
938 691179 en
939 834143 en
940 671295 en
941 553087 en
942 835786 zh
943 845887 en
944 613583 fr
945 818659 pt
946 749004 fr
947 581644 en
948 678458 ja
949 726429 es
950 672322 ja
951 514995 en
952 836950 es
953 662237 ko
954 633515 nl
955 801557 en
956 615658 en
957 467909 en
958 685274 ja
959 553592 en
960 684281 en
961 781816 ja
962 808667 ja
963 663866 en
964 583116 en
965 825997 en
966 829358 en
967 720407 en
968 522931 en
969 839436 en
970 742391 fr
971 712124 fr
972 685264 en
973 508943 en
974 629017 en
975 667257 es
976 680813 da
977 795853 en
978 607259 en
979 625169 en
980 591634 en
981 809340 en
982 834404 en
983 736073 en
984 654739 ko
985 844636 en
986 646207 en
987 809717 de
988 766105 da
989 693827 en
990 649409 en
991 559581 en
992 613098 es
993 653594 es
994 800497 en
995 768726 es
996 591273 en
997 820511 en
998 539565 en
999 628704 ko
1000 602223 en
1001 741124 fr
1002 739542 en
1003 672582 en
1004 842033 ko
1005 459151 en
1006 795813 de
1007 585216 en
1008 768334 it
1009 523936 fr
1010 481879 en
1011 672741 en
1012 604360 ko
1013 843241 ja
1014 776527 en
1015 807196 en
1016 497698 en
1017 424277 fr
1018 846214 en
1019 379686 en
1020 665753 fr
1021 591274 en
1022 454527 fr
1023 698201 ja
1024 865921 zh
1025 601329 en
1026 745881 th
1027 574060 en
1028 591275 en
1029 477044 en
1030 630240 fr
1031 617502 en
1032 681349 de
1033 678580 es
1034 547565 en
1035 849236 ru
1036 489932 en
1037 635731 en
1038 776305 ja
1039 842171 th
1040 774714 en
1041 774343 fr
1042 735726 fr
1043 649394 en
1044 631843 en
1045 695089 ja
1046 659988 fr
1047 730840 en
1048 577242 fr
1049 568620 en
1050 823754 en
1051 579741 ja
1052 811072 es
1053 795607 zh
1054 791568 en
1055 845222 ko
1056 760883 de
1057 693113 en
1058 638449 en
1059 834027 en
1060 645689 en
1061 736074 en
1062 653457 hi
1063 436969 en
1064 630392 en
1065 451048 en
1066 607844 ko
1067 513692 cn
1068 724885 ko
1069 559907 en
1070 616651 en
1071 785539 en
1072 774021 en
1073 669666 en
1074 763152 es
1075 830991 en
1076 835551 en
1077 847143 ja
1078 449406 en
1079 760747 no
1080 729720 fr
1081 730028 sv
1082 779202 pt
1083 763149 en
1084 597433 it
1085 753601 fr
1086 717693 en
1087 794602 en
1088 768744 ja
1089 747983 ja
1090 624789 en
1091 682532 en
1092 675445 en
1093 550988 en
1094 623135 ko
1095 595743 en
1096 676705 fr
1097 727745 en
1098 712120 fr
1099 574078 hu
1100 573164 es
1101 482373 en
1102 802121 de
1103 724331 it
1104 788929 is
1105 592863 en
1106 599925 hi
1107 711963 en
1108 776503 en
1109 696605 en
1110 633503 nl
1111 805411 en
1112 861057 en
1113 849369 en
1114 835112 en
1115 857729 en
1116 768127 fr
1117 619297 en
1118 637534 fr
1119 579047 en
1120 758866 ja
1121 809970 pl
1122 797815 en
1123 645788 en
1124 716594 en
1125 778819 da
1126 410113 en
1127 772388 es
1128 850099 en
1129 863851 es
1130 822099 en
1131 776660 en
1132 773736 en
1133 662712 en
1134 682376 en
1135 666243 en
1136 645710 en
1137 565028 en
1138 602334 fr
1139 853791 fr
1140 844069 ko
1141 853354 en
1142 661595 pt
1143 848278 en
1144 628914 en
1145 760873 de
1146 866462 en
1147 828305 en
1148 845875 pl
1149 653349 en
1150 866408 zh
1151 347626 en
1152 852719 en
1153 852721 en
1154 837548 en
1155 806690 en
1156 869250 en
1157 575842 ru
1158 841755 en
1159 523638 en
1160 566525 en
1161 870404 en
1162 744275 en
1163 619778 en
1164 788669 el
1165 785457 en
1166 588228 en
1167 744278 it
1168 675319 en
1169 735981 en
1170 713711 en
1171 870096 zh
1172 869602 en
1173 593910 en
1174 643532 en
1175 660942 no
1176 668640 es
1177 745611 fr
1178 735716 fr
1179 663260 fr
1180 726916 sv
1181 756651 fr
1182 773543 ru
1183 581726 en
1184 856117 de
1185 738652 en
1186 609490 ru
1187 668408 it
1188 763148 en
1189 842050 pl
1190 730769 fr
1191 597891 en
1192 659954 fr
1193 795530 en
1194 853588 de
1195 862855 zh
1196 680531 fr
1197 855823 de
1198 856437 ar
1199 843906 en
1200 438631 en
1201 671043 fr
1202 730823 ko
1203 739990 en
1204 875104 zh
1205 784376 it
1206 647581 en
1207 865140 es
1208 659370 da
1209 670981 es
1210 749274 en
1211 826796 en
1212 601470 en
1213 846867 en
1214 646376 en
1215 468225 en
1216 806804 en
1217 524369 en
1218 597316 en
1219 660708 it
1220 785752 en
1221 712454 fr
1222 786705 pt
1223 748787 de
1224 811076 en
1225 766423 ja
1226 750253 en
1227 608980 it
1228 866038 en
1229 567748 en
1230 512025 en
1231 567690 en
1232 753453 en
1233 877657 en
1234 818543 en
1235 848886 en
1236 370172 en
1237 749386 fr
1238 788942 fr
1239 869617 fr
1240 740925 en
1241 785210 fr
1242 580489 en
1243 797457 en
1244 779029 zh
1245 511819 es
1246 672521 en
1247 639721 en
1248 695080 en
1249 785663 en
1250 763873 en
1251 857702 en
1252 670429 en
1253 890601 en
1254 831438 en
1255 871875 en
1256 655082 fr
1257 833420 it
1258 843338 de
1259 654344 it
1260 592695 sv
1261 787310 en
1262 628964 ja
1263 796428 en
1264 858815 id
1265 874948 tr
1266 766798 es
1267 795778 en
1268 423333 en
1269 831405 en
1270 649928 en
1271 473021 en
1272 800410 es
1273 839100 ja
1274 568124 en
1275 660120 no
1276 617653 en
1277 780382 en
1278 776328 it
1279 768331 it
1280 576925 ru
1281 482321 en
1282 610253 en
1283 793937 de
1284 749645 en
1285 452019 en
1286 823609 en
1287 820722 es
1288 598826 hi
1289 602295 ko
1290 744746 en
1291 669671 en
1292 660000 fr
1293 542178 en
1294 821859 it
1295 576845 en
1296 617762 en
1297 582292 en
1298 583081 en
1299 792678 ja
1300 785538 pt
1301 618162 en
1302 866678 pl
1303 554594 en
1304 600583 en
1305 541524 en
1306 752070 fr
1307 864873 en
1308 871964 pl
1309 516329 en
1310 823610 en
1311 650031 da
1312 633844 ja
1313 838154 fa
1314 797838 en
1315 881460 en
1316 796499 en
1317 739901 en
1318 660353 en
1319 609972 en
1320 623511 no
1321 776279 es
1322 787723 en
1323 588182 fi
1324 795522 en
1325 741335 ja
1326 714195 en
1327 761898 ja
1328 855400 ta
1329 524434 en
1330 661591 fr
1331 746131 fr
1332 512195 en
1333 885110 en
1334 728054 en
1335 793998 fr
1336 522402 en
1337 716612 en
1338 743873 it
1339 763788 en
1340 776541 sq
1341 818192 en
1342 734265 en
1343 811592 en
1344 861126 ru
1345 821792 en
1346 592508 hi
1347 877013 en
1348 785544 ja
1349 877004 en
1350 585245 en
1351 498402 fr
1352 719463 fr
1353 659384 ru
1354 828264 it
1355 654974 en
1356 537116 en
1357 895435 zh
1358 763109 sv
1359 876716 en
1360 763164 en
1361 860867 en
1362 798544 ja
1363 660833 en
1364 660262 no
1365 718838 en
1366 777270 en
1367 879330 en
1368 877183 en
1369 897429 en
1370 795815 ka
1371 896633 en
1372 763025 en
1373 820709 fr
1374 594691 fr
1375 833404 fr
1376 749142 uk
1377 718633 en
1378 425909 en
1379 892113 en
1380 762433 en
1381 614917 en
1382 591222 cn
1383 818415 ru
1384 785533 en
1385 887645 pt
1386 655302 fi
1387 761548 en
1388 801271 en
1389 632617 en
1390 765869 en
1391 767377 hi
1392 874260 en
1393 894155 en
1394 460458 en
1395 850356 en
1396 645886 en
1397 644495 en
1398 807867 fr
1399 615666 en
1400 802217 en
1401 722778 it
1402 715874 it
1403 884452 ar
1404 856321 pt
1405 874124 en
1406 801604 ko
1407 920081 en

#### Variables a conciderar
- adult (2)
- original_lenguaje (4)
- title (3)
- keywords (5)
- popularity (3)
- date (year) (3)
- director (5)
- actors (5)
- vote_average (3)
- vote_count (3)
- Gender (7)
-------------------------
43

## Validate distance between movies

In [35]:
def crear_indice_annoy(vectores, n_arboles=10):
    """Crea índice Annoy"""
    dimension = vectores.shape[1]
    idx = AnnoyIndex(dimension, 'angular')  # 'angular' = similitud coseno
    
    for i, vec in enumerate(vectores):
        idx.add_item(i, vec)
    
    idx.build(n_arboles)
    return idx

def buscar_similares_annoy(indice, vector, k=5):
    """Busca k vecinos más cercanos"""
    return indice.get_nns_by_vector(vector, k, include_distances=True)

In [36]:
indice = crear_indice_annoy(np.vstack(df_vectorized['movie_vector'].values))

In [37]:
batman_vector_test = df_vectorized.iloc[110]['movie_vector']
buscar_similares_annoy(indice, batman_vector_test,5)

([110, 3718, 3295, 1309, 1949],
 [0.000295598671073094,
  0.2637985050678253,
  0.3083724081516266,
  0.31121954321861267,
  0.31370118260383606])

In [40]:
movie_df.iloc[143]

id                                                                 144
id_tmdb                                                         502425
adult                                                                0
backdrop_path                         /vwbmp3vvX4U0VjinaQktYOBt5kW.jpg
original_lenguaje                                                   en
overview             South Africa, 1978. Tim Jenkin and Stephen Lee...
keywords             ['imprisoned apartheid', 'lee white', 'tim jen...
popularity                                                       1.980
poster_path                           /8GGS0jkFFCnmdStvZED6NL6V7gd.jpg
release_date                                                2020-03-06
title                                             Escape from Pretoria
director                                                 Francis Annan
actors               ['Daniel Radcliffe', 'Daniel Webber', 'Ian Har...
vote_average                                                     7.180
vote_count                                                        1440
image_path           Data/img_recommendMe/502425_escape_from_pretor...
created_at                                         2026-01-29 15:11:24
Name: 143, dtype: object

## Make Test

In [41]:
indice = crear_indice_annoy(np.vstack(df_vectorized['movie_vector'].values))

In [42]:
test_movie = movie_df[movie_df['title'].str.contains('Sonic')]
test_movie

,id,id_tmdb,adult,backdrop_path,original_lenguaje,overview,keywords,popularity,poster_path,release_date,title,director,actors,vote_average,vote_count,image_path,created_at
85,86,454626,0,/stmYfCUGd8Iy6kAMBr6AmWqx8Bq.jpg,en,"Powered with incredible speed, Sonic The Hedge...","['sonic hedgehog', 'stop robotnik', 'vs super'...",10.221,/aQvJ5WPzZgYVDrxLX4R6cLJCEaQ.jpg,2020-02-12,Sonic the Hedgehog,Jeff Fowler,"['Ben Schwartz', 'James Marsden', 'Tika Sumpte...",7.292,10226,Data/img_recommendMe/454626_sonic_the_hedgehog...,2026-01-29 15:10:02
1647,1648,675353,0,/xuLA0pii2IMJW2puT7EvJtgpg0H.jpg,en,"After settling in Green Hills, Sonic is eager ...","['hills sonic', 'knuckles search', 'robotnik r...",11.295,/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg,2022-03-30,Sonic the Hedgehog 2,Jeff Fowler,"['Ben Schwartz', 'James Marsden', 'Tika Sumpte...",7.442,5747,Data/img_recommendMe/675353_sonic_the_hedgehog...,2026-01-29 15:50:19
3741,3743,939243,0,/noPEm6Vu9Lm6QUdTGLOyRgk4M6s.jpg,en,"Sonic, Knuckles, and Tails reunite against a p...","['sonic knuckles', 'tails reunite', 'adversary...",18.190,/d8Ryb8AunYAuycVKDp5HpdWPKgC.jpg,2024-12-19,Sonic the Hedgehog 3,Jeff Fowler,"['Jim Carrey', 'Ben Schwartz', 'Keanu Reeves',...",7.632,3118,Data/img_recommendMe/939243_sonic_the_hedgehog...,2026-01-29 16:51:07

In [43]:
movie = movie_df.iloc[85]
movie

id                                                                  86
id_tmdb                                                         454626
adult                                                                0
backdrop_path                         /stmYfCUGd8Iy6kAMBr6AmWqx8Bq.jpg
original_lenguaje                                                   en
overview             Powered with incredible speed, Sonic The Hedge...
keywords             ['sonic hedgehog', 'stop robotnik', 'vs super'...
popularity                                                      10.221
poster_path                           /aQvJ5WPzZgYVDrxLX4R6cLJCEaQ.jpg
release_date                                                2020-02-12
title                                               Sonic the Hedgehog
director                                                   Jeff Fowler
actors               ['Ben Schwartz', 'James Marsden', 'Tika Sumpte...
vote_average                                                     7.292
vote_count                                                       10226
image_path           Data/img_recommendMe/454626_sonic_the_hedgehog...
created_at                                         2026-01-29 15:10:02
Name: 85, dtype: object

In [44]:
test = df_vectorized.iloc[85]['movie_vector']
buscar_similares_annoy(indice, test,5)

([85, 1647, 1433, 2530, 1823],
 [0.00031008184305392206,
  0.231051966547966,
  0.28900814056396484,
  0.32614538073539734,
  0.34970614314079285])

In [48]:
close_movie = movie_df.iloc[1823]
close_movie

id                                                                1824
id_tmdb                                                         616037
adult                                                                0
backdrop_path                         /jsoz1HlxczSuTx0mDl2h0lxy36l.jpg
original_lenguaje                                                   en
overview             After his retirement is interrupted by Gorr th...
keywords             ['thor odinson', 'god butcher', 'valkyrie korg...
popularity                                                      11.506
poster_path                           /pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg
release_date                                                2022-07-06
title                                           Thor: Love and Thunder
director                                                 Taika Waititi
actors               ['Chris Hemsworth', 'Natalie Portman', 'Christ...
vote_average                                                     6.400
vote_count                                                        8334
image_path           Data/img_recommendMe/616037_thor_love_and_thun...
created_at                                         2026-01-29 15:54:58
Name: 1823, dtype: object

### Get CSV from Database

In [32]:
conexion = mysql.connector.connect(**config)
cursor = conexion.cursor()
consulta = "SELECT * FROM Movie_Genres"
cursor.execute(consulta)

results = cursor.fetchall()
column_names = [desc[0] for desc in cursor.description]

movie_Genres_df = pd.DataFrame(results, columns=column_names)

In [33]:
movie_df.to_csv("../movies_db.csv", index=False)
movie_Genres_df.to_csv("../movie_Genres_df.csv", index=False)
df_vectorized.to_csv("../vectorized_movies_df.csv", index=False)

### Another Test

In [47]:
import numpy as np
import faiss

In [1]:
import numpy as np
import faiss

d = 64
xb = np.random.rand(100, d).astype("float32")
xq = np.random.rand(1, d).astype("float32")

index = faiss.IndexFlatL2(d)
index.add(xb)

D, I = index.search(xq, 5)

print(I)
print(D)

numpy: 1.24.4
faiss: 1.7.4
[[90 19 32  9  7]]
[[6.948475 7.21723  7.513218 7.604233 8.011496]]

In [33]:
import faiss

In [34]:
d = 43
index = faiss.IndexFlatL2(d)
index.add(np.vstack(df_vectorized['movie_vector'].values))

In [55]:
movie = movie_df.iloc[85]
movie

id                                                                  86
id_tmdb                                                         454626
adult                                                                0
backdrop_path                         /stmYfCUGd8Iy6kAMBr6AmWqx8Bq.jpg
original_lenguaje                                                   en
overview             Powered with incredible speed, Sonic The Hedge...
keywords             ['sonic hedgehog', 'stop robotnik', 'vs super'...
popularity                                                      10.221
poster_path                           /aQvJ5WPzZgYVDrxLX4R6cLJCEaQ.jpg
release_date                                                2020-02-12
title                                               Sonic the Hedgehog
director                                                   Jeff Fowler
actors               ['Ben Schwartz', 'James Marsden', 'Tika Sumpte...
vote_average                                                     7.292
vote_count                                                       10226
image_path           Data/img_recommendMe/454626_sonic_the_hedgehog...
created_at                                         2026-01-29 15:10:02
Name: 85, dtype: object

In [65]:
query = df_vectorized.iloc[85]['movie_vector']
query = np.array(query, dtype=np.float32).reshape(1, -1)

D, I = index.search(query, 15)
print(I)
print(D)

[[  85 1647 1433 1328  858 1823 2530  370 1062  289    3 1275 2549 3741
   933]]
[[  0.      138.53696 207.89484 231.19183 316.73822 324.18002 342.31445
  355.5838  380.36615 389.02966 407.78305 412.7419  418.01248 436.53098
  442.67505]]

In [ ]:
3741

In [69]:
movie = movie_df.iloc[2549]
movie

id                                                                2551
id_tmdb                                                         447277
adult                                                                0
backdrop_path                         /lAs4Y5a8Pi86xDwuv8cx2prOVI2.jpg
original_lenguaje                                                   en
overview             The youngest of King Triton’s daughters, and t...
keywords             ['ariel', 'sea witch', 'triton daughters', 'da...
popularity                                                      11.966
poster_path                           /ym1dxyOk4jFcSl4Q2zmRrA5BEEN.jpg
release_date                                                2023-05-18
title                                               The Little Mermaid
director                                                  Rob Marshall
actors               ['Halle Bailey', 'Jonah Hauer-King', 'Melissa ...
vote_average                                                     6.277
vote_count                                                        3231
image_path           Data/img_recommendMe/447277_the_little_mermaid...
created_at                                         2026-01-29 16:16:23
Name: 2549, dtype: object

In [ ]:
[85, 1647, 1433, 2530, 1823]

In [54]:
movie = movie_df.iloc[1823]
movie

id                                                                1824
id_tmdb                                                         616037
adult                                                                0
backdrop_path                         /jsoz1HlxczSuTx0mDl2h0lxy36l.jpg
original_lenguaje                                                   en
overview             After his retirement is interrupted by Gorr th...
keywords             ['thor odinson', 'god butcher', 'valkyrie korg...
popularity                                                      11.506
poster_path                           /pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg
release_date                                                2022-07-06
title                                           Thor: Love and Thunder
director                                                 Taika Waititi
actors               ['Chris Hemsworth', 'Natalie Portman', 'Christ...
vote_average                                                     6.400
vote_count                                                        8334
image_path           Data/img_recommendMe/616037_thor_love_and_thun...
created_at                                         2026-01-29 15:54:58
Name: 1823, dtype: object